import type { Lang } from '@/context/LanguageContext'

export const heroBackgroundUrl = '/assets/images/hero-closet-clean.png'

export const siteCopy = {
  en: {
    header: {
      brandTag: 'Your premium AI wardrobe',
      nav: {
        home: 'Home',
        closet: 'My Closet',
        stylist: 'AI Stylist',
        outfits: 'Outfits',
        profile: 'Profile',
      },
      dashboard: 'Dashboard',
    },
    home: {
      badge: 'Luxury fashion house meets advanced AI intelligence',
      title: 'ClosetAI transforms your wardrobe into a living personal style intelligence system.',
      description:
        'Beyond outfit suggestions, ClosetAI builds a luxury digital wardrobe memory: it captures garments, learns your style behavior, adapts to context, and improves recommendations over time.',
      heroIntroLabel: 'Personal AI wardrobe intelligence',
      heroIntroTitle: 'Welcome To Your Personal AI Fashion House',
      heroIntroDescription:
        'Step into a premium experience where wardrobe structure, daily context, and personal taste come together to produce refined recommendations that feel truly yours.',
      ctas: {
        closet: 'Enter My Closet',
        stylist: 'Explore AI Stylist',
        dashboard: 'Open Control Room',
        journey: 'Start Your Journey',
        howItWorks: 'See How It Works',
        assistant: 'Open AI Stylist',
      },
      metrics: [
        { label: 'Decision intelligence', value: 'Weather + occasion + personal style memory' },
        { label: 'Wardrobe intelligence', value: 'Capture, detect, organize, learn, recommend' },
      ],
      assistant: {
        label: 'AI Assistant',
        title: 'What should I wear today?',
        text: 'Let’s create a polished look based on your real day, your weather, and the style profile you are building.',
      },
      panelLabel: 'What the product does',
      panelItems: [
        { icon: '📸', title: 'Photograph garments', text: 'Bring physical clothing into a structured digital wardrobe.' },
        { icon: '🧠', title: 'AI recognition', text: 'Identify category, color, style, and wardrobe context automatically.' },
        { icon: '👔', title: 'Build complete looks', text: 'Generate polished outfits instead of isolated clothing suggestions.' },
        { icon: '🛍️', title: 'Show what is missing', text: 'Recommend the next wardrobe additions that improve the whole closet.' },
      ],
      vision: {
        label: 'The vision',
        title: 'A premium product journey built around personal style evolution.',
        text: 'ClosetAI is designed as one connected flow: structure the wardrobe, understand context, generate refined looks, and continuously improve style intelligence over time.',
        cards: [
          { tag: 'Step 1', title: 'Build the smart wardrobe memory', text: 'Capture garments and structure them beautifully so the system understands exactly what you own.' },
          { tag: 'Step 2', title: 'Read daily context with precision', text: 'Combine occasion, weather, schedule, and style mood in one elegant decision layer.' },
          { tag: 'Step 3', title: 'Compose complete premium looks', text: 'Deliver coherent outfits with purpose, not disconnected item suggestions.' },
          { tag: 'Step 4', title: 'Evolve personal style intelligence', text: 'Learn from choices, detect patterns, and sharpen recommendations with every interaction.' },
        ],
      },
      capabilities: {
        label: 'Core capabilities',
        title: 'The platform now follows the real product intelligence order.',
        cards: [
          { tag: 'Closet', title: 'Digitize and organize garments', text: 'A clean category structure turns your wardrobe into a usable, intelligent data foundation.' },
          { tag: 'Stylist', title: 'Generate looks from real context', text: 'Recommendations use event, weather, and profile intelligence before suggesting any look.' },
          { tag: 'Outfits', title: 'Build a reusable style memory', text: 'Saved outfits become training signals for future recommendations and style pattern detection.' },
          { tag: 'Profile', title: 'Refine your fashion identity', text: 'Preferences and feedback become a persistent memory layer that personalizes each next decision.' },
        ],
      },
      roadmap: {
        label: 'Roadmap',
        title: 'The path from luxury product to adaptive personal style intelligence.',
        cards: [
          { step: '0', title: 'Foundation', text: 'Project, codebase, GitHub, and the first live website.' },
          { step: '1', title: 'Brand and design', text: 'Logo, luxury visual direction, and polished user experience.' },
          { step: '2', title: 'User profile', text: 'Registration, preferences, and personalized style learning.' },
          { step: '3', title: 'Smart closet', text: 'Photo capture, AI recognition, and wardrobe organization.' },
          { step: '4', title: 'AI stylist', text: 'Looks based on weather, schedule, event, and personal style.' },
          { step: '5', title: 'Marketplace', text: 'Buying, selling, renting, and intelligent product recommendations.' },
          { step: '6', title: 'Accessibility', text: 'Support for color blindness, low vision, and voice-first guidance.' },
          { step: '7', title: 'Mobile app', text: 'iOS and Android launch with store-ready experience.' },
        ],
      },
      about: {
        badge: 'Why this matters',
        title: 'ClosetAI is not a website. It is the first layer of a personal fashion intelligence operating system.',
        paragraphs: [
          'The product guides users through a purposeful flow: profile identity, wardrobe structure, context-aware styling, outfit memory, and continuous refinement.',
          'Built in Israel with a luxury-fashion perspective and engineered for future database, AI learning, and recommendation intelligence at scale.',
        ],
        ctas: { dashboard: 'View Product Journey', closet: 'Start With My Closet' },
      },
    },
    dashboard: {
      badge: 'Control room',
      title: 'Your personal style intelligence command center.',
      description: 'See the full product loop in one premium view: structure wardrobe data, style with context, save outcomes, and train your personal style engine.',
      ctas: { closet: 'My Closet', stylist: 'AI Stylist', outfits: 'Outfits' },
      summary: [
        { label: 'Now', title: 'Structured wardrobe memory', text: 'Organize garments into a reliable data foundation the AI can actually reason about.' },
        { label: 'Next', title: 'Context-aware daily styling', text: 'Use weather, occasion, and personal preferences to generate better recommendations.' },
        { label: 'Later', title: 'Adaptive recommendation engine', text: 'Transform outfit history and behavior into predictive personal style intelligence.' },
      ],
      cards: [
        { title: 'Smart Closet', text: 'Start by capturing and organizing garments into categories the AI can understand.' },
        { title: 'AI Stylist', text: 'Generate looks using occasion, weather, and the personal signals learned from your wardrobe.' },
        { title: 'Outfits', text: 'Review curated outfit directions and compare polished looks for different moments.' },
        { title: 'Profile', text: 'Refine colors, silhouettes, and preferences so the system becomes more accurate over time.' },
      ],
      footer: 'ClosetAI is being built as a luxury-grade personal fashion intelligence platform.',
    },
    closet: {
      splash: 'My Closet',
      title: 'My Closet',
      subtitle: 'Your personal smart wardrobe',
      description: 'Build a clean digital wardrobe foundation: every item you add improves precision, recommendation quality, and long-term style learning.',
      addItem: '+ Add New Item',
      emptyTitle: 'Your wardrobe is ready for its first luxury piece',
      emptyText: 'Start with your first item so ClosetAI can begin building your personal wardrobe memory and style intelligence.',
      emptyCta: '+ Add New Item',
      itemsCountLabel: 'items',
      process: [
        { step: '01', title: 'Capture', text: 'Add garments with clear naming, visuals, and style metadata.' },
        { step: '02', title: 'Structure', text: 'Create category clarity so the AI can read relationships between pieces.' },
        { step: '03', title: 'Learn', text: 'Each organized item becomes signal quality for better styling decisions.' },
      ],
    },
    categoryPage: {
      notFound: 'Category not found.',
      back: 'Back to My Closet',
      description: 'Pieces in this part of your wardrobe, ready for better outfit decisions.',
      addItem: '+ Add New Item',
      addedOn: 'Added on',
      season: 'Season',
      empty: 'No items have been added to this category yet.',
    },
    aiStylist: {
      back: 'Back',
      splash: 'AI Stylist',
      title: 'Your Personal AI Stylist',
      question: 'What should I wear today?',
      description: 'Choose occasion and weather to generate a premium recommendation and feed your long-term style intelligence profile.',
      cards: [
        { title: 'Occasion layer', text: 'Teach the system whether this is work, date, event, casual, or sport.' },
        { title: 'Weather layer', text: 'Balance warmth, comfort, and polish before the AI builds the final look.' },
      ],
      occasion: 'Occasion',
      weather: 'Weather',
      occasionHint: 'Select your day context',
      weatherHint: 'Select your weather',
      occasionOptions: [
        { value: 'Work', label: 'Work' },
        { value: 'Date', label: 'Date' },
        { value: 'Event', label: 'Event' },
        { value: 'Casual', label: 'Casual' },
        { value: 'Sport', label: 'Sport' },
      ],
      weatherOptions: [
        { value: 'Sunny', label: 'Sunny' },
        { value: 'Cold', label: 'Cold' },
        { value: 'Rainy', label: 'Rainy' },
      ],
      submit: 'Create My Outfit',
      resultTitle: 'Recommended Outfit',
      resultReason: 'Why this works: it aligns your occasion, weather needs, and a refined wardrobe direction.',
      saveLook: 'Save To Style Memory',
      closetCta: 'Review My Closet',
    },
    profile: {
      splash: 'Profile',
      title: 'My Style Profile',
      description: 'Manage identity, preferences, and personal signals that power your evolving ClosetAI recommendation engine.',
      cards: [
        { title: 'Favorite Colors', text: 'Black, Navy, Ivory' },
        { title: 'Style Mood', text: 'Minimal luxury / Work-ready' },
        { title: 'AI learning', text: 'The system refines recommendations from your choices and wardrobe habits.' },
      ],
      settings: [
        { label: 'Style preferences', value: 'Minimal luxury, tailored, polished casual' },
        { label: 'Favorite colors', value: 'Black, ivory, champagne gold, navy' },
        { label: 'Language settings', value: 'Hebrew / English with full RTL-LTR support' },
      ],
      intelligence: {
        label: 'AI Learning Readiness',
        title: 'Style Intelligence Snapshot',
        wardrobeItems: 'Wardrobe items',
        outfitHistory: 'Outfit history',
        combinations: 'Favorite combinations',
      },
      futureLabel: 'What comes next',
      futureTitle: 'Future personalization will unify profile, wardrobe behavior, outfit history, and recommendation intelligence.',
      futureText: 'The goal is one adaptive memory layer across the full product, not disconnected settings on isolated screens.',
      futureStack: [
        'Authentication and account identity',
        'Cloud database for wardrobe memory',
        'AI image recognition for clothing detection',
        'Weather API integration for daily context',
        'Personal recommendations engine',
      ],
    },
    outfits: {
      splash: 'Outfits',
      title: 'Your Outfit Collection',
      description: 'A premium archive for saved looks, behavior signals, and future AI-generated recommendations.',
      cards: [
        { label: 'Work', title: 'Sleek tailored every day', text: 'Dark blazer, crisp shirt and polished shoes for confident office styling.' },
        { label: 'Date', title: 'Soft luxury with charm', text: 'Timeless textures, subtle tailoring and a rich autumn palette.' },
        { label: 'Rainy', title: 'Structured layers with warmth', text: 'Weather-ready coat, elegant knit and refined neutral accessories.' },
      ],
      bottom: 'Each saved outfit is both a luxury recommendation and a training signal for smarter future styling.',
      cta: 'Ask the Stylist',
      savedLabel: 'Saved Looks',
      generatedLabel: 'Future AI Collection',
    },
    addItem: {
      title: 'Add New Item',
      description: 'Capture or upload an image, add item details, and save it directly into your smart closet.',
      itemSource: 'How do you want to add this item?',
      takePhoto: 'Take Photo',
      takePhotoHint: 'Camera flow is prepared for upcoming AI capture integration.',
      uploadImage: 'Upload Image',
      uploadHint: 'Choose an image file from your device.',
      cameraReady: 'Camera integration is coming soon. You can continue with image upload for now.',
      name: 'Item Name',
      category: 'Category',
      color: 'Color',
      style: 'Style',
      brand: 'Brand',
      brandPlaceholder: 'Optional for now (future-ready)',
      season: 'Season',
      image: 'Item Image',
      imageMissingHint: 'No image uploaded yet. You can still save this item with metadata only.',
      fullOutfitPhotoToggle: 'This image is a full outfit photo (prepare clothing separation)',
      fullOutfitPhotoHint: 'ClosetAI will prepare this photo for future AI separation into shirt, pants, shoes, jacket, and accessories.',
      preparedForSeparation: 'Prepared successfully: this photo is queued for future item separation.',
      cancel: 'Cancel',
      save: 'Save Item',
      newItem: 'New Item',
      defaultColor: 'Black',
      defaultStyle: 'Casual',
      seasons: {
        spring: 'Spring',
        summer: 'Summer',
        autumn: 'Autumn',
        winter: 'Winter',
        allSeason: 'All Season',
      },
      images: { blazer: 'Blazer', shirt: 'Shirt', chinos: 'Chinos' },
    },
    language: {
      label: 'Language',
      title: 'Select your interface language',
      description: 'Choose the language for your ClosetAI experience.',
      hebrew: 'Hebrew',
      english: 'English',
    },
    onboarding1: {
      splash: 'Welcome to ClosetAI',
      title: 'Welcome to the future of the smart closet',
      text: 'A few short steps to prepare your personal wardrobe and start AI styling.',
      next: 'Continue',
    },
    onboarding2: {
      splash: 'Choose language',
      title: 'Choose your preferred language',
      text: 'This choice will control text direction and the full product experience.',
    },
    onboarding3: {
      splash: 'Style preferences',
      title: 'Define your personal style',
      text: 'Choose the fashion direction that represents you and the AI will recommend accordingly.',
      save: 'Save and continue',
      options: [
        { value: 'Minimal', label: 'Minimal' },
        { value: 'Luxury', label: 'Luxury' },
        { value: 'Streetwear', label: 'Streetwear' },
        { value: 'Business', label: 'Business' },
        { value: 'Sport', label: 'Sport' },
      ],
    },
    onboarding4: {
      splash: 'Finish setup',
      title: 'Your smart closet is almost ready',
      text: 'Final settings before receiving looks and a more personal styling experience.',
      language: 'Language',
      style: 'Style',
      openCloset: 'Open My Closet',
    },
    categories: {
      shirts: { label: 'Shirts', description: 'The top layer of your look.' },
      pants: { label: 'Pants', description: 'The foundation of every outfit.' },
      shoes: { label: 'Shoes', description: 'The finishing touch to elevate any look.' },
      jackets: { label: 'Jackets', description: 'Smart layers for every season.' },
      accessories: { label: 'Accessories', description: 'The details that complete your style.' },
    },
  },
  he: {
    header: {
      brandTag: 'הארון החכם שלך עם AI',
      nav: {
        home: 'בית',
        closet: 'הארון שלי',
        stylist: 'סטייליסט AI',
        outfits: 'לוקים',
        profile: 'פרופיל',
      },
      dashboard: 'דשבורד',
    },
    home: {
      badge: 'בית אופנה יוקרתי פוגש אינטליגנציית AI מתקדמת',
      title: 'ClosetAI הופכת את הארון שלך למערכת אינטליגנציה סגנונית אישית וחיה.',
      description:
        'מעבר להמלצת לבוש נקודתית, ClosetAI בונה זיכרון דיגיטלי יוקרתי לארון: מצלמת, מבינה, לומדת דפוסי בחירה ומשפרת המלצות לאורך זמן.',
      heroIntroLabel: 'אינטליגנציית מלתחה אישית מבוססת AI',
      heroIntroTitle: 'ברוכים הבאים לבית האופנה האישי שלכם עם AI',
      heroIntroDescription:
        'חוויה פרימיום שמחברת בין סדר בארון, הקשר יומיומי וטעם אישי כדי לייצר המלצות לבוש מדויקות שמרגישות באמת שלך.',
      ctas: {
        closet: 'כניסה לארון שלי',
        stylist: 'לגלות את הסטייליסט',
        dashboard: 'פתיחת חדר הבקרה',
        journey: 'התחל את המסע שלך',
        howItWorks: 'ראה איך זה עובד',
        assistant: 'פתח את הסטייליסט',
      },
      metrics: [
        { label: 'אינטליגנציית החלטה', value: 'מזג אוויר + אירוע + זיכרון סגנוני אישי' },
        { label: 'אינטליגנציית מלתחה', value: 'צילום, זיהוי, סידור, למידה והמלצה' },
      ],
      assistant: {
        label: 'עוזר AI',
        title: 'מה כדאי לי ללבוש היום?',
        text: 'בוא נבנה לוק מדויק לפי היום שלך, מזג האוויר והפרופיל הסגנוני שנבנה עבורך לאורך זמן.',
      },
      panelLabel: 'מה המוצר עושה',
      panelItems: [
        { icon: '📸', title: 'צילום בגדים', text: 'הופכים את הבגדים הפיזיים לארון דיגיטלי מסודר.' },
        { icon: '🧠', title: 'זיהוי AI', text: 'זיהוי אוטומטי של קטגוריה, צבע, סגנון והקשר בארון.' },
        { icon: '👔', title: 'בניית לוקים מלאים', text: 'יוצרים הופעה שלמה ולא רק הצעת פריט בודד.' },
        { icon: '🛍️', title: 'השלמות חכמות', text: 'ממליצים מה חסר כדי לשדרג את הארון כולו.' },
      ],
      vision: {
        label: 'החזון',
        title: 'מסע מוצר יוקרתי שנבנה סביב התפתחות סגנון אישית.',
        text: 'ClosetAI נבנית כחוויה רציפה אחת: מבנה מלתחה מדויק, הבנת הקשר יומיומי, יצירת לוקים והעמקת אינטליגנציית הסגנון לאורך זמן.',
        cards: [
          { tag: 'שלב 1', title: 'בניית זיכרון מלתחה חכם', text: 'מעלים בגדים ומסדרים אותם כדי לתת למערכת הבנה מדויקת של מה שבאמת קיים אצלך.' },
          { tag: 'שלב 2', title: 'קריאת הקשר יומיומי', text: 'מחברים אירוע, מזג אוויר, לו״ז ומצב סגנוני לשכבת החלטה אחת ומדויקת.' },
          { tag: 'שלב 3', title: 'הרכבת לוקים פרימיום מלאים', text: 'מקבלים הופעה שלמה עם כוונה והיגיון, לא רשימת פריטים מנותקת.' },
          { tag: 'שלב 4', title: 'התפתחות אינטליגנציה אישית', text: 'לומדים מהבחירות שלך, מזהים דפוסים ומחדדים כל המלצה עתידית.' },
        ],
      },
      capabilities: {
        label: 'יכולות מרכזיות',
        title: 'הפלטפורמה מסודרת לפי סדר האינטליגנציה האמיתי של המוצר.',
        cards: [
          { tag: 'ארון', title: 'דיגיטציה וסידור של הבגדים', text: 'מבנה קטגוריות נקי הופך את הארון שלך לבסיס נתונים שה-AI באמת יודע להבין.' },
          { tag: 'סטייליסט', title: 'יצירת לוקים מתוך הקשר אמיתי', text: 'ההמלצה מחברת אירוע, מזג אוויר ופרופיל אישי לפני כל החלטת לבוש.' },
          { tag: 'לוקים', title: 'בניית זיכרון סגנוני חוזר', text: 'לוקים שמורים הופכים לאותות למידה שמחדדים המלצות עתידיות.' },
          { tag: 'פרופיל', title: 'חידוד זהות אופנתית אישית', text: 'העדפות ופידבק נשמרים כשכבת זיכרון מתמשכת שמדייקת את המערכת.' },
        ],
      },
      roadmap: {
        label: 'מפת הדרך',
        title: 'הדרך ממוצר יוקרה למנוע אינטליגנציה סגנונית אדפטיבי.',
        cards: [
          { step: '0', title: 'בסיס', text: 'פרויקט, קוד, GitHub והאתר החי הראשון.' },
          { step: '1', title: 'מיתוג ועיצוב', text: 'לוגו, כיוון חזותי יוקרתי וחוויית משתמש מלוטשת.' },
          { step: '2', title: 'פרופיל משתמש', text: 'הרשמה, העדפות ולמידת סגנון אישית.' },
          { step: '3', title: 'ארון חכם', text: 'צילום בגדים, זיהוי AI וסידור הארון.' },
          { step: '4', title: 'סטייליסט AI', text: 'לוקים לפי מזג אוויר, לו״ז, אירוע וסגנון אישי.' },
          { step: '5', title: 'מרקטפלייס', text: 'קנייה, מכירה, השכרה והמלצות חכמות.' },
          { step: '6', title: 'נגישות', text: 'תמיכה בעיוורון צבעים, לקויות ראייה והכוונה קולית.' },
          { step: '7', title: 'אפליקציה', text: 'השקה ל-iOS ו-Android עם חוויה מוכנה לחנויות.' },
        ],
      },
      about: {
        badge: 'למה זה חשוב',
        title: 'ClosetAI היא לא אתר. היא השכבה הראשונה במערכת אינטליגנציית אופנה אישית.',
        paragraphs: [
          'המוצר מוביל את המשתמש בזרימה אחת מדויקת: זהות אישית, מבנה מלתחה, סטיילינג הקשרי, זיכרון לוקים ושיפור מתמשך.',
          'נבנה בישראל מזווית אופנתית-יוקרתית, ומתוכנן להתחבר בהמשך למסד נתונים, למידת AI ומנוע המלצות אישי בקנה מידה רחב.',
        ],
        ctas: { dashboard: 'צפייה במסע המוצר', closet: 'להתחיל מהארון שלי' },
      },
    },
    dashboard: {
      badge: 'חדר הבקרה',
      title: 'מרכז השליטה של אינטליגנציית הסגנון האישית שלך.',
      description: 'כאן רואים את לולאת המוצר המלאה במקום אחד: מבנה ארון, סטיילינג לפי הקשר, שמירת תוצאות והכשרת מנוע ההמלצות האישי שלך.',
      ctas: { closet: 'הארון שלי', stylist: 'סטייליסט AI', outfits: 'לוקים' },
      summary: [
        { label: 'עכשיו', title: 'זיכרון מלתחה מובנה', text: 'סידור פריטים לבסיס נתונים אמין שהמערכת יכולה להסיק ממנו.' },
        { label: 'הבא', title: 'סטיילינג יומי מבוסס הקשר', text: 'אירוע, מזג אוויר והעדפות אישיות מתחברים להמלצה מדויקת יותר.' },
        { label: 'בהמשך', title: 'מנוע המלצות אדפטיבי', text: 'היסטוריית לוקים והתנהגות משתמש הופכות לאינטליגנציה סגנונית אישית.' },
      ],
      cards: [
        { title: 'ארון חכם', text: 'מתחילים מלכידת בגדים וסידורם לקטגוריות שה-AI יודע להבין.' },
        { title: 'סטייליסט AI', text: 'יוצרים לוקים לפי אירוע, מזג אוויר והאותות האישיים שנלמדים מהארון.' },
        { title: 'לוקים', text: 'משווים כיווני לבוש מלוטשים למצבים שונים לאורך היום.' },
        { title: 'פרופיל', text: 'מעדכנים צבעים, גזרות והעדפות כדי שהמערכת תהיה מדויקת יותר לאורך זמן.' },
      ],
      footer: 'ClosetAI נבנית כפלטפורמת אינטליגנציית אופנה אישית ברמת פרימיום.',
    },
    closet: {
      splash: 'הארון שלי',
      title: 'הארון שלי',
      subtitle: 'המלתחה החכמה האישית שלך',
      description: 'כאן בונים את בסיס הנתונים של הסטייל שלך: כל פריט חדש משפר דיוק, איכות המלצות ולמידה אישית לאורך זמן.',
      addItem: '+ הוספת פריט חדש',
      emptyTitle: 'הארון שלך מוכן לפריט היוקרתי הראשון',
      emptyText: 'הוסף את הפריט הראשון כדי ש-ClosetAI תתחיל לבנות את זיכרון המלתחה והאינטליגנציה האישית שלך.',
      emptyCta: '+ הוספת פריט חדש',
      itemsCountLabel: 'פריטים',
      process: [
        { step: '01', title: 'קליטה', text: 'מוסיפים בגדים עם שם ברור, תמונה ומטא-דאטה סגנוני.' },
        { step: '02', title: 'מבנה', text: 'מייצרים היררכיית קטגוריות שהמערכת יודעת להבין לעומק.' },
        { step: '03', title: 'למידה', text: 'כל פריט מסודר הופך לאות איכות שמחדד החלטות סטיילינג עתידיות.' },
      ],
    },
    categoryPage: {
      notFound: 'הקטגוריה לא נמצאה.',
      back: 'חזרה לארון שלי',
      description: 'הפריטים בחלק הזה של הארון מוכנים להחלטות לבוש טובות יותר.',
      addItem: '+ הוספת פריט חדש',
      addedOn: 'נוסף בתאריך',
      season: 'עונה',
      empty: 'עדיין לא נוספו פריטים לקטגוריה הזו.',
    },
    aiStylist: {
      back: 'חזרה',
      splash: 'סטייליסט AI',
      title: 'הסטייליסט האישי שלך עם AI',
      question: 'מה כדאי לי ללבוש היום?',
      description: 'בחר אירוע ומזג אוויר כדי לייצר המלצה יוקרתית ומדויקת וגם להעשיר את פרופיל הלמידה הסגנוני שלך.',
      cards: [
        { title: 'שכבת האירוע', text: 'מלמדים את המערכת אם זה יום עבודה, דייט, אירוע, קז׳ואל או ספורט.' },
        { title: 'שכבת מזג האוויר', text: 'מאזנים בין חום, נוחות ומראה מלוטש לפני בניית הלוק.' },
      ],
      occasion: 'אירוע',
      weather: 'מזג אוויר',
      occasionHint: 'בחר את ההקשר של היום',
      weatherHint: 'בחר את תנאי מזג האוויר',
      occasionOptions: [
        { value: 'Work', label: 'עבודה' },
        { value: 'Date', label: 'דייט' },
        { value: 'Event', label: 'אירוע' },
        { value: 'Casual', label: 'יומיומי' },
        { value: 'Sport', label: 'ספורט' },
      ],
      weatherOptions: [
        { value: 'Sunny', label: 'שמשי' },
        { value: 'Cold', label: 'קר' },
        { value: 'Rainy', label: 'גשום' },
      ],
      submit: 'צור לי לוק',
      resultTitle: 'לוק מומלץ',
      resultReason: 'למה זה עובד: זה מחבר בין האירוע, תנאי מזג האוויר וכיוון לבוש יוקרתי ומדויק.',
      saveLook: 'שמירה לזיכרון הסגנון',
      closetCta: 'חזרה לארון שלי',
    },
    profile: {
      splash: 'פרופיל',
      title: 'פרופיל הסגנון שלי',
      description: 'כאן מנהלים זהות, העדפות ואותות אישיים שמפעילים את מנוע ההמלצות המתפתח של ClosetAI.',
      cards: [
        { title: 'צבעים אהובים', text: 'שחור, כחול כהה, שנהב' },
        { title: 'אופי סגנוני', text: 'יוקרה מינימליסטית / מוכן לעבודה' },
        { title: 'למידת AI', text: 'המערכת משפרת המלצות לפי הבחירות וההרגלים שלך בארון.' },
      ],
      settings: [
        { label: 'העדפות סגנון', value: 'יוקרה מינימליסטית, מחויט, קז׳ואל מדויק' },
        { label: 'צבעים אהובים', value: 'שחור, שנהב, זהב שמפניה, כחול כהה' },
        { label: 'הגדרות שפה', value: 'עברית / אנגלית עם תמיכה מלאה ב-RTL ו-LTR' },
      ],
      futureLabel: 'מה בהמשך',
      futureTitle: 'הפרסונליזציה תחבר בין הפרופיל, התנהגות הארון, היסטוריית הלוקים ומנוע ההמלצות.',
      futureText: 'המטרה היא שכבת זיכרון אדפטיבית אחת לכל המוצר, לא הגדרות מבודדות במסכים נפרדים.',
      intelligence: {
        label: 'מוכנות למידת AI',
        title: 'תמונת מצב אינטליגנציית סגנון',
        wardrobeItems: 'פריטים בארון',
        outfitHistory: 'היסטוריית לוקים',
        combinations: 'קומבינציות מועדפות',
      },
      futureStack: [
        'אימות משתמשים וזהות חשבון',
        'מסד נתונים ענני לזיכרון הארון',
        'זיהוי תמונה מבוסס AI לפריטי לבוש',
        'אינטגרציית API של מזג אוויר',
        'מנוע המלצות אישיות',
      ],
    },
    outfits: {
      splash: 'לוקים',
      title: 'אוסף הלוקים שלך',
      description: 'ארכיון יוקרתי ללוקים שמורים, אותות התנהגות ולוקים עתידיים שייוצרו על ידי AI.',
      cards: [
        { label: 'עבודה', title: 'מראה מחויט לכל יום', text: 'בלייזר כהה, חולצה נקייה ונעליים מלוטשות ליום משרד בטוח.' },
        { label: 'דייט', title: 'יוקרה רכה עם נוכחות', text: 'טקסטורות נצחיות, תפירה עדינה ופלטת סתיו עשירה.' },
        { label: 'גשום', title: 'שכבות מסודרות עם חמימות', text: 'מעיל מוכן למזג האוויר, סריג אלגנטי ואקססוריז ניטרליים מדויקים.' },
      ],
      bottom: 'כל לוק שנשמר הוא גם המלצה יוקרתית וגם אות למידה שמחדד את ההמלצות הבאות.',
      cta: 'שאל את הסטייליסט',
      savedLabel: 'לוקים שמורים',
      generatedLabel: 'אוסף AI עתידי',
    },
    addItem: {
      title: 'הוספת פריט חדש',
      description: 'צלם או העלה תמונה, הוסף פרטי פריט ושמור אותו ישירות בארון החכם שלך.',
      itemSource: 'איך תרצה להוסיף את הפריט?',
      takePhoto: 'צילום תמונה',
      takePhotoHint: 'תשתית המצלמה מוכנה לשילוב AI עתידי.',
      uploadImage: 'העלאת תמונה',
      uploadHint: 'בחר קובץ תמונה מהמכשיר שלך.',
      cameraReady: 'שילוב מצלמה יתווסף בקרוב. בינתיים אפשר להמשיך עם העלאת תמונה.',
      name: 'שם הפריט',
      category: 'קטגוריה',
      color: 'צבע',
      style: 'סגנון',
      brand: 'מותג',
      brandPlaceholder: 'אופציונלי בשלב זה (מוכן לעתיד)',
      season: 'עונה',
      image: 'תמונת הפריט',
      imageMissingHint: 'עדיין לא הועלתה תמונה. אפשר לשמור את הפריט גם על בסיס פרטי מטא-דאטה בלבד.',
      fullOutfitPhotoToggle: 'התמונה הזו היא לוק מלא (הכנה להפרדת פריטים)',
      fullOutfitPhotoHint: 'ClosetAI תכין את התמונה להפרדה עתידית של חולצה, מכנסיים, נעליים, ז׳קט ואקססוריז.',
      preparedForSeparation: 'בוצעה הכנה בהצלחה: התמונה נכנסה לתור להפרדת פריטים בעתיד.',
      cancel: 'ביטול',
      save: 'שמירת פריט',
      newItem: 'פריט חדש',
      defaultColor: 'שחור',
      defaultStyle: 'יומיומי',
      seasons: {
        spring: 'אביב',
        summer: 'קיץ',
        autumn: 'סתיו',
        winter: 'חורף',
        allSeason: 'כל העונות',
      },
      images: { blazer: 'בלייזר', shirt: 'חולצה', chinos: 'צ׳ינו' },
    },
    language: {
      label: 'שפה',
      title: 'בחירת שפת הממשק',
      description: 'בחר את השפה לחוויית ClosetAI שלך.',
      hebrew: 'עברית',
      english: 'אנגלית',
    },
    onboarding1: {
      splash: 'ברוכים הבאים ל-ClosetAI',
      title: 'ברוך הבא לעתיד של הארון החכם',
      text: 'כמה צעדים קצרים כדי להכין את הארון האישי שלך ולהתחיל סטיילינג עם AI.',
      next: 'המשך',
    },
    onboarding2: {
      splash: 'בחירת שפה',
      title: 'בחר את השפה המועדפת עליך',
      text: 'הבחירה הזו תשפיע על כיוון הטקסט ועל כל חוויית המוצר.',
    },
    onboarding3: {
      splash: 'העדפות סגנון',
      title: 'הגדר את הסגנון האישי שלך',
      text: 'בחר את הכיוון האופנתי שמייצג אותך וה-AI ימליץ בהתאם.',
      save: 'שמור והמשך',
      options: [
        { value: 'Minimal', label: 'מינימליסטי' },
        { value: 'Luxury', label: 'יוקרתי' },
        { value: 'Streetwear', label: 'סטריטוור' },
        { value: 'Business', label: 'עסקי' },
        { value: 'Sport', label: 'ספורטיבי' },
      ],
    },
    onboarding4: {
      splash: 'סיום ההגדרות',
      title: 'הארון החכם שלך כמעט מוכן',
      text: 'עוד הגדרות אחרונות לפני שמתחילים לקבל לוקים וחוויית סטיילינג אישית.',
      language: 'שפה',
      style: 'סגנון',
      openCloset: 'פתח את הארון שלי',
    },
    categories: {
      shirts: { label: 'חולצות', description: 'השכבה העליונה של הלוק שלך.' },
      pants: { label: 'מכנסיים', description: 'הבסיס של כל הופעה.' },
      shoes: { label: 'נעליים', description: 'הנגיעה שמרימה כל לוק.' },
      jackets: { label: 'ז׳קטים', description: 'שכבות חכמות לכל עונה.' },
      accessories: { label: 'אקססוריז', description: 'הפרטים שמשלימים את הסגנון שלך.' },
    },
  },
} as const satisfies Record<Lang, unknown>

export function getSiteCopy(lang: Lang) {
  return siteCopy[lang]
}